`timescale 1ns/1ps
//
// supercycle_tb.v — simple per-JSON-config testbench for run_sim.py
//
// Instantiates the DUT, applies a config produced by run_sim.py, runs
// exactly ONE supercycle (super_repeat_limit=1), and logs every posedge
// to sim/tb_output.csv.
//
// sim/generated_stimulus.v MUST be generated by run_sim.py before compilation.
// It defines:
//   localparam TIMEOUT_CYCLES = ...;
//   task apply_config; ... endtask

module supercycle_tb;

// ---------------------------------------------------------------------------
// DUT parameters (must match RTL defaults)
// ---------------------------------------------------------------------------
localparam MAX_CYCLE_TYPES = 8;
localparam MAX_SLOTS       = 16;
localparam MAX_SEQ_LEN     = 32;
localparam NUM_MARKERS     = 3;

// ---------------------------------------------------------------------------
// DUT signals
// ---------------------------------------------------------------------------
reg        clk;
reg        reset_n;
reg  [6:0] avs_address;
reg        avs_write;
reg        avs_read;
reg [31:0] avs_writedata;
wire [31:0] avs_readdata;
wire        aom_rp_out, aom_ro_out, mw_out, veto_out, sync_out;
wire [NUM_MARKERS-1:0] marker_out;

// ---------------------------------------------------------------------------
// DUT instantiation
// ---------------------------------------------------------------------------
pulse_sequencer_avalon #(
    .MAX_CYCLE_TYPES (MAX_CYCLE_TYPES),
    .MAX_SLOTS       (MAX_SLOTS),
    .MAX_SEQ_LEN     (MAX_SEQ_LEN),
    .NUM_MARKERS     (NUM_MARKERS)
) uut (
    .clk              (clk),
    .reset_n          (reset_n),
    .avs_s0_address   (avs_address),
    .avs_s0_write     (avs_write),
    .avs_s0_writedata (avs_writedata),
    .avs_s0_read      (avs_read),
    .avs_s0_readdata  (avs_readdata),
    .aom_rp_out       (aom_rp_out),
    .aom_ro_out       (aom_ro_out),
    .mw_out           (mw_out),
    .veto_out         (veto_out),
    .sync_out         (sync_out),
    .marker_out       (marker_out)
);

// ---------------------------------------------------------------------------
// 50 MHz clock  (period = 20 ns)
// ---------------------------------------------------------------------------
initial clk = 0;
always #10 clk = ~clk;

// ---------------------------------------------------------------------------
// Avalon-MM bus tasks  (identical to comprehensive testbench)
// ---------------------------------------------------------------------------
task write_reg;
    input [6:0]  addr;
    input [31:0] data;
    begin
        @(negedge clk);
        avs_address   = addr;
        avs_writedata = data;
        avs_write     = 1;
        @(negedge clk);
        avs_write     = 0;
    end
endtask

// ---------------------------------------------------------------------------
// Include generated stimulus (defines TIMEOUT_CYCLES and apply_config task)
// ---------------------------------------------------------------------------
`include "generated_stimulus.v"

// ---------------------------------------------------------------------------
// CSV logging
// ---------------------------------------------------------------------------
integer csv_fd;

initial begin
    // Initialise bus
    reset_n       = 0;
    avs_address   = 0;
    avs_write     = 0;
    avs_read      = 0;
    avs_writedata = 0;

    // Open output CSV
    csv_fd = $fopen("sim/tb_output.csv", "w");
    $fwrite(csv_fd, "time_ns,rp,ro,mw,veto,sync,mk0,mk1,mk2\n");

    // Reset sequence
    repeat(5) @(negedge clk);
    reset_n = 1;
    repeat(5) @(negedge clk);

    // Write BRAM + sequence registers via generated task
    apply_config();

    // Override super_repeat_limit to 1 so we run exactly one supercycle
    write_reg(7'h01, 32'd1);

    // Start the sequencer
    write_reg(7'h00, 32'd1);

    // Wait for the STARTUP state to finish (BRAM prefetch, STARTUP_CYCLES clocks).
    // This keeps the CSV free of meaningless idle time before the first cycle fires.
    repeat(STARTUP_CYCLES) @(posedge clk);

    // Sample every posedge for RUNNING_CYCLES (one full supercycle + margin).
    // sync_out is ACTIVE-LOW in the RTL; invert it so CSV column = 1 when pulse is active.
    // Time: $realtime is in nanoseconds with timescale 1ns/1ps.
    repeat(RUNNING_CYCLES) begin
        @(posedge clk);
        $fwrite(csv_fd, "%0.0f,%b,%b,%b,%b,%b,%b,%b,%b\n",
            $realtime,
            aom_rp_out, aom_ro_out, mw_out, veto_out, ~sync_out,
            marker_out[0], marker_out[1], marker_out[2]);
    end

    $fclose(csv_fd);
    $finish;
end

endmodule
